name: 'Test Issue Labeler'
on:
    workflow_dispatch:
        inputs:
            sync-scope-labels:
                description: 'Sync scope labels'
                required: true
                type: number
            issue-number:
                description: 'Issue number to label'
                required: true
                type: number

permissions:
    contents: write
    issues: write

jobs:
    label_update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: ./
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
                  enable-versioned-regex: 0
                  include-title: 1
                  sync-labels: 1
                  include-body: 0
                  sync-scope-labels: ${{ inputs.sync-scope-labels }}
                  issue-number: ${{ inputs.issue-number }}
