name: 'Update Github Issue Labels'
on:
    issues:
        types: [opened, edited]

jobs:
    label_update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            
            - name: Configure Git User
              run: |
                git config --global user.name 'LabelBot'
                git config --global user.email 'labelbot@bartonmalow.com'
            
            - uses: ./
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
                  enable-versioned-regex: 0
                  include-title: 1
                  sync-labels: 1
                  include-body: 0
                  sync-scope-labels: 1
                  issue-number: ${{ github.event.issue.number }}
